version: '3.9'

services:
  nestappdal:
    container_name: customersdal
    image: customersdal:1.0.0
    build: ./CustomersDAL
    ports:
      - 3000:3000
    environment:
      - DB_TYPE=postgres
      - PG_HOST=customerdb 
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
    depends_on:
      - customerdb

  nestapphl:
    container_name: customershl
    image: customershl:1.0.0
    build: ./CustomersHL
    ports:
      - 3001:3001
    environment:
      - DB_TYPE=postgres
      - PG_HOST=customerdb 
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
    depends_on:
      - customerdb

  customerdb:
    container_name: customerdb
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
